const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGELANGUAGE: "CHANGELANGUAGE",

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    GET_TOP_DOCTOR_START: "GET_TOP_DOCTOR_START",
    GET_TOP_DOCTOR_SUCCESS: "GET_TOP_DOCTOR_SUCCESS",
    GET_TOP_DOCTOR_FAILED: "GET_TOP_DOCTOR_FAILED",

    //Admin
    GET_GENDER_START: "GET_GENDER_START",
    GET_GENDER_SUCCESS: "GET_GENDER_SUCCESS",
    GET_GENDER_FAILED: "GET_GENDER_FAILED",

    GET_POSITION_START: "GET_POSITION_START",
    GET_POSITION_SUCCESS: "GET_POSITION_SUCCESS",
    GET_POSITION_FAILED: "GET_POSITION_FAILED",

    GET_ROLE_START: "GET_ROLE_START",
    GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
    GET_ROLE_FAILED: "GET_ROLE_FAILED",

    CREATE_USER_START: "CREATE_USER_START",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILED: "CREATE_USER_FAILED",

    UPDATE_USER_START: "UPDATE_USER_START",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

    GET_ALL_USER_START: "GET_ALL_USER_START",
    GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
    GET_ALL_USER_FAILED: "GET_ALL_USER_FAILED",

    DELETE_USER_START: "DELETE_USER_START",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILED: "DELETE_USER_FAILED",
})

export default actionTypes;